site_name: Kirastar - 深空摄影系列笔记
repo_url: https://github.com/ZhenHuangLab/Kirastar
repo_name: ZhenHuangLab/Kirastar
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 Zhen Huang

theme:
  name: material
  custom_dir: overrides
  language: zh
  favicon: assets/icons/favicon.svg
  icon:
    logo: material/telescope
    repo: fontawesome/brands/git-alt
    edit: material/pencil-circle 
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至黑夜模式 Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: 切换至白天模式 Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.action.edit
    - announce.dismiss
extra:
  social:
      - icon: fontawesome/solid/house
        link: https://zhenhuang.site
      - icon: fontawesome/brands/github
        link: https://github.com/ZhenHuangLab
      - icon: fontawesome/brands/bilibili
        link: https://space.bilibili.com/37168500
      - icon: fontawesome/brands/x-twitter
        link: https://twitter.com/ZhenVictorHuang
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/profile.php?id=100095427284684

  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem # improves the detection of Markup to emphasize text in Markdown using special characters
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - git-committers:
      repository: ZhenHuangLab/Kirastar
      branch: main
  - git-authors

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/katex.js 
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - 主页: 
    - index.md
    - 测试1: test1.md
    - 测试2: 
      - test2.md
      - 测试3: test3.md
  - 前期: 'test.md'