name: ci
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai
  MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material 
      - run: pip install mkdocs-git-revision-date-localized-plugin
      # - run: pip3 install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - name: Setup IndexNow
        run: |
          echo ${{ secrets.INDEXNOW_KEY }} > ./site/${{ secrets.INDEXNOW_KEY }}.txt
      - run: mkdocs gh-deploy --force
