name: 'IndexNow'
on:
  push:
    branches:
        - main
  schedule:
    # Set the schedule time
    - cron: '0 0,12 * * *'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://kirastar.zhenhuang.site/sitemap.xml"
          endpoint: "www.bing.com"
          since: 1
          since-unit: "month"
          key: "d86a8cc8bd824c5bb49ffcb0950759f0"
          key-location: "https://kirastar.zhenhuang.site/d86a8cc8bd824c5bb49ffcb0950759f0.txt"